package VIEW;

import BUS.Usuario;
import DAO.UsuarioDAO;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.tree.TreePath;

/**
 *
 * @author philipe.pompeu
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();        
        try {
            boolean pedirUser = true;
            
            while(pedirUser)
            {
                if(!logadoComSucesso())
                {
                    String mensagem = "Usuário/Senha errado. Deseja tentar novamente?";
                    int dialogResult = JOptionPane.showConfirmDialog (null, mensagem,"Aviso",JOptionPane.YES_NO_OPTION);
                    pedirUser = dialogResult == JOptionPane.YES_OPTION;                    
                }else
                {
                    pedirUser = false;
                }                    
            }    
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + e.getCause(),"Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean logadoComSucesso() throws Exception
    {   
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date today = Calendar.getInstance().getTime();
        String reportDate = df.format(today);
        this.lblDataLogin.setText("Data: "+ reportDate);
        
        JTextField userName = new JTextField();
        Object[] message = {"Usuário e Senha", userName};        
        String password = JOptionPane.showInputDialog(this, message, "Login", JOptionPane.OK_CANCEL_OPTION);          
        if (validUser(userName.getText(),password))
        {
            this.lblNomeUsuario.setText("Usuário : "+userName.getText());
            return true;
        }else
        {
            return false;
        }
    }
    
    private boolean validUser(String username, String pass) throws Exception
    {    
        boolean result = false;
        
        Usuario teste = new UsuarioDAO().Consultar(username);
        
        if (!teste.getNome().isEmpty()) {
            
            MessageDigest m;        
            m = MessageDigest.getInstance("MD5");
            m.update(pass.getBytes(),0,pass.length());            
            String rightPass = String.format("%1$032X", new BigInteger(1,m.digest()));            
            result = teste.getSenha().contains(rightPass);
        }
        
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscrollTree = new javax.swing.JScrollPane();
        jTreePrincipal = new javax.swing.JTree();
        jtabPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblDataLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Loja ACME");
        setName("framePrincipal"); // NOI18N
        setResizable(false);

        jscrollTree.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Loja ACME");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastros");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fornecedores");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Produtos");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lançamentos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Pedido de Venda");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreePrincipal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreePrincipal.setToolTipText("");
        jTreePrincipal.setScrollsOnExpand(false);
        jTreePrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreePrincipalMouseClicked(evt);
            }
        });
        jscrollTree.setViewportView(jTreePrincipal);

        jtabPrincipal.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário Logado"));
        jPanel1.setToolTipText("");

        lblNomeUsuario.setText("jLabel1");

        lblDataLogin.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataLogin)
                    .addComponent(lblNomeUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jscrollTree, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jscrollTree, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreePrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreePrincipalMouseClicked
        
        TreePath tp = jTreePrincipal.getPathForLocation(evt.getX(), evt.getY());
        
        if (tp.getPathCount() == 3) {
            String titulo = tp.getLastPathComponent().toString();                        
            frmBase novo; 
            try {
             switch(titulo)
                {
                    case"Usuarios":
                        novo = new frmUsuarios();
                    break;
                    case"Produtos":
                        novo = new frmProdutos();
                    break;
                    case"Fornecedores":
                        novo = new frmFornecedores();
                    break;
                    case"Clientes":
                        novo = new frmClientes();
                    break;
                    case"Pedido de Venda":
                        novo = new frmPedidos();
                    break;                        
                    default:
                        novo = new frmBase();
                    break;
                }               

                if (!procurarTab(titulo))
                {
                    jtabPrincipal.add(titulo, novo);
                    jtabPrincipal.setSelectedIndex(jtabPrincipal.getTabCount() - 1);
                }    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage() + e.getCause(),"Aviso",JOptionPane.ERROR_MESSAGE);
            }
             
                                
        }
    }//GEN-LAST:event_jTreePrincipalMouseClicked
    
    private boolean procurarTab(String titulo)
    {
        boolean result = false;
        
        for (int i = 0; i < jtabPrincipal.getTabCount(); i++) {
            if (jtabPrincipal.getTitleAt(i) == titulo)
            {
                jtabPrincipal.setSelectedIndex(i);
                return true;
            }
            
        }
        
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {                    
                   TelaPrincipal nova = new TelaPrincipal();
                   nova.setLocationRelativeTo(null);
                   nova.setVisible(true);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTree jTreePrincipal;
    private javax.swing.JScrollPane jscrollTree;
    private javax.swing.JTabbedPane jtabPrincipal;
    private javax.swing.JLabel lblDataLogin;
    private javax.swing.JLabel lblNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
